### ISSUE TITLE
csdtk4.2 download pages down

### ISSUE THREAD

**Issue by GammaTek** [Ai-Thinker-Open/GPRS_C_SDK_DOC#6]
All download pages are down: baidu, MEGA cloud as well as direct link. Download of csdtk is not possible

**Comment by ivanxuu** [comment]
Hi, I've been looking for the CSDTK today and I couldn't find it anywhere.
But I just come across this repo [https://github.com/pulkin/csdtk42-linux](https://github.com/pulkin/csdtk42-linux), but I don't know if the content is exactly the same as `CSDTK42_Linux.tar.gz`.
I don't even have my a9g board yet. So I'm not going to try. But just in case is useful to you.

**Comment by tejpochiraju** [comment]
Hi all - we are excited to release our firmware framework and documentation for the A9 as open source. Feel free to adopt, adapt and contribute.

Blog: https://iotready.co/blog/a9-gsm-gps-iot-module-library/
Github Repo: https://github.com/IoTReady/a9_gsm_gps_library
Documentation: https://iotready.co/a9_gsm_gps_library/

Cheers,

Tej
